### ISSUE TITLE
Non absorbing gases correction

### ISSUE THREAD

**Issue by fnemina** [fnemina/AtmosphericCorrection#1]
[Atmospheric Correction for Satellite Ocean Color Radiometry](https://oceancolor.gsfc.nasa.gov/docs/AtmosphericCorrectionTutorial.pdf) - 6.1

**Comment by fnemina** [comment]
The current state of the cross comparation between `pyOSOAA` and the NASA OBPG algorithm is the following, with strong diferences in the NIR-SWIR region.

```python
import numpy as np
import pyOSOAA
import pyNASAOBPG
import matplotlib.pyplot as plt
from pyOSOAA.osoaahelpers import RunWavelengths
from matplotlib.ticker import StrMethodFormatter, NullFormatter

s = pyOSOAA.OSOAA()

# pyOSOAA object
view = 0
# Angles configuration
s.view.phi = 90
s.ang.thetas = 40

# Sea bottom configuration
s.sea.depth = 0.05
s.sea.bottype = 1
s.sea.botalb = 0

# Sea particles configuration
s.phyto.chl = 0
s.sed.csed = 0
s.det.abs440 = 0
s.ys.abs440 = 0

# Sea surface configuration
s.sea.wind = 5

# Small optical thickness
s.ap.SetPressure(1013.25)
s.aer.aotref = 0.00001

# Set view level at TOA
s.view.level = 1
rhor0 = RunWavelengths(s, wl/1000, view)/np.cos(np.pi*view/180.0)
```

```python
plt.ion()
fig, ax = plt.subplots(figsize=(7.5,5))
ray = pyNASAOBPG.RAYLEIGHLUT('sabiamar', '/home/fnemina/tmp/LUT-NASA/')
wl = ray.getWavelength()
plt.plot(wl, ray.getRadiance(wind=5, thetas=40, thetav=0, phi=90), 'o', label=r"$\theta_v=0$")
#plt.plot(wl, ray.getRadiance(wind=5, thetas=40, thetav=20, phi=90), 'o', label=r"$\theta_v=20$")
#plt.plot(wl, ray.getRadiance(wind=5, thetas=40, thetav=40, phi=90), 'o', label=r"$\theta_v=40$")
#plt.plot(wl, ray.getRadiance(wind=5, thetas=40, thetav=60, phi=90), 'o', label=r"$\theta_v=60$")

plt.gca().set_prop_cycle(None)

plt.plot(wl, rhor0, '-', label=r"Simulated")
#plt.plot(wl, rhor20, '-', label=r"Simulated")
#plt.plot(wl, rhor40, '-', label=r"Simulated")
#plt.plot(wl, rhor60, '-', label=r"Simulated")


plt.xlabel(r"$\lambda[nm]$")
plt.ylabel(r"$\rho$")

plt.legend(loc='upper center',
          ncol=4, fancybox=True,framealpha=1)
plt.title(r"$\theta_0=40^\circ$, $W=5m/s$, $\Delta\phi=90^\circ$")

ax.set_xlabel(r"$\log \lambda[nm]$")
ax.set_ylabel(r"$\log \rho$")


plt.savefig("fig_ray.png",dpi=300, transparent=False)
plt.show()
```
![fig_ray](https://user-images.githubusercontent.com/2727433/54286657-fb8e9000-4582-11e9-9481-70518d588dbe.png)

```python
plt.ion()
fig, ax = plt.subplots(figsize=(7.5,5))
ray = pyNASAOBPG.RAYLEIGHLUT('sabiamar', '/home/fnemina/tmp/LUT-NASA/')
wl = ray.getWavelength()

plt.plot(wl, ray.getRadiance(wind=5, thetas=40, thetav=0, phi=90), 'o', label=r"$\theta_v=0$")
#plt.plot(wl, ray.getRadiance(wind=5, thetas=40, thetav=20, phi=90), 'o', label=r"$\theta_v=20$")
#plt.plot(wl, ray.getRadiance(wind=5, thetas=40, thetav=40, phi=90), 'o', label=r"$\theta_v=40$")
#plt.plot(wl, ray.getRadiance(wind=5, thetas=40, thetav=60, phi=90), 'o', label=r"$\theta_v=60$")

plt.gca().set_prop_cycle(None)

plt.plot(wl, rhor0, '-', label=r"Simulated")
#plt.plot(wl, rhor20, '-', label=r"Simulated")
#plt.plot(wl, rhor40, '-', label=r"Simulated")
#plt.plot(wl, rhor60, '-', label=r"Simulated")

plt.xlabel(r"$\lambda[nm]$")
plt.ylabel(r"$\rho$")

plt.legend(loc='upper center',
          ncol=4, fancybox=True,framealpha=1)
plt.title(r"$\theta_0=40^\circ$, $W=5m/s$, $\Delta\phi=90^\circ$")

ax.set_xlabel(r"$\log \lambda[nm]$")
ax.set_ylabel(r"$\log \rho$")

ax.set_xscale('log')
ax.set_yscale('log')
ax.xaxis.set_major_formatter(StrMethodFormatter('{x:.0f}'))
ax.xaxis.set_minor_formatter(NullFormatter())

plt.xticks([400,600,800,1000,1200,1400,1600],[400,600,800,1000,1200,1400,1600],rotation=0)
plt.yticks([0.1,0.01,0.001],[0.1,0.01,0.001])
plt.savefig("fig_logray.png",dpi=300, transparent=False)
plt.show()
```

![fig_logray](https://user-images.githubusercontent.com/2727433/54286682-09dcac00-4583-11e9-85ee-5a4ffc629df3.png)

```python
plt.ion()
fig, ax = plt.subplots(figsize=(7.5,5))
ray = pyNASAOBPG.RAYLEIGHLUT('sabiamar', '/home/fnemina/tmp/LUT-NASA/')
wl = ray.getWavelength()
plt.plot(wl, ray.getRadiance(wind=5, thetas=40, thetav=0, phi=90) - rhor0, 'o', label=r"$\theta_v=0$")

plt.xlabel(r"$\lambda[nm]$")
plt.ylabel(r"$Diferencia$")

plt.legend(loc='upper center',
          ncol=4, fancybox=True,framealpha=1)
plt.title(r"$\theta_0=40^\circ$, $W=5m/s$, $\Delta\phi=90^\circ$")

plt.savefig("fig_difray.png",dpi=300, transparent=False)
plt.show()
```

![fig_difray](https://user-images.githubusercontent.com/2727433/54286708-17923180-4583-11e9-8790-1364b2319d3b.png)

**Comment by fnemina** [comment]
We improve the results by substracting the surface reflectance. There is still a residual error that we suspect might come from molecular-aerosol multiple scattering. We could try to remove it using the SOS. Also, this effect might come from the difference in the RT codes used to solve the radiative transfer equation.

```python
# pyOSOAA object
view = 0
# Angles configuration
s.view.phi = 90
s.ang.thetas = 40

# Sea bottom configuration
s.sea.depth = 0.05
s.sea.bottype = 1
s.sea.botalb = 0

# Sea particles configuration
s.phyto.chl = 0
s.sed.csed = 0
s.det.abs440 = 0
s.ys.abs440 = 0

# Sea surface configuration
s.sea.wind = 5

# Small optical thickness
s.ap.SetPressure(1013.25)
s.aer.aotref = 0.00001

# Set view level at TOA
s.view.level = 1
rhor0 = RunWavelengths(s, wl/1000, view)

# Set view level at TOA
s.view.level = 3
surface = RunWavelengths(s, wl/1000, view)
rhor0 =rhor0 - surface
```
we do this for view = 0, 20, 40 and 60 and make the same plots as before

![fig_ray](https://user-images.githubusercontent.com/2727433/54299393-8aa6a280-4599-11e9-877e-467b96536418.png)

![fig_logray](https://user-images.githubusercontent.com/2727433/54299399-8d08fc80-4599-11e9-84a8-46f2f1836148.png)

![fig_difray](https://user-images.githubusercontent.com/2727433/54299406-9003ed00-4599-11e9-9705-ad11d01140d8.png)

**Comment by fnemina** [comment]
We improved the calculation of the surface reflectance by removing only the glint component without any atmosphere (aot = 0, mot = 0.0005)

```python
def rayleigh(view):
    # Angles configuration
    s.view.phi = 90
    s.ang.thetas = 40

    # Sea bottom configuration
    s.sea.depth = 0.05
    s.sea.bottype = 1
    s.sea.botalb = 0

    # Sea particles configuration
    s.phyto.chl = 0
    s.sed.csed = 0
    s.det.abs440 = 0
    s.ys.abs440 = 0

    # Sea surface configuration
    s.sea.wind = 5

    # Small optical thickness
    s.ap.SetPressure(1013.25)
    s.aer.aotref = 0.0

    # Set view level at TOA
    s.view.level = 1
    rhor0 = RunWavelengths(s, wl/1000, view)
    T = np.exp(-s.outputs.profileatm.tau[-1]*(1/np.cos(np.pi*view/180.0)+1/np.cos(np.pi*s.ang.thetas/180.0)))
    # Set view level at TOA
    s.ap.SetMot(0.0005)
    s.view.level = 3
    surface = RunWavelengths(s, wl/1000, view)*T
    return rhor0 - surface

rhor0 = rayleigh(0)
rhor20 = rayleigh(20)
rhor40 = rayleigh(40)
rhor60 = rayleigh(60)
```
![fig_ray](https://user-images.githubusercontent.com/2727433/54303305-6ea6ff00-45a1-11e9-8f20-09b0031db47b.png)

![fig_logray](https://user-images.githubusercontent.com/2727433/54303304-6e0e6880-45a1-11e9-8225-a309721b5158.png)

![fig_difray](https://user-images.githubusercontent.com/2727433/54303302-6e0e6880-45a1-11e9-9ada-c9ad804384d2.png)

**Comment by fnemina** [comment]
We improve again the molecular scattering by turning the ocean into a truly absorbing one. We also used the optical thickness defined in the Seadas LUTs.

```python
def rayleigh(view, wl, sun=40, phi=90, wind=5, table=True):
    s = pyOSOAA.OSOAA()
    # Angles configuration
    s.view.phi = phi
    s.ang.thetas = sun

    # Sea bottom configuration
    s.sea.depth = 0.05
    s.sea.bottype = 1
    s.sea.botalb = 0

    # Sea particles configuration
    s.phyto.chl = 0
    s.sed.csed = 0
    s.det.abs440 = 1e5
    s.ys.abs440 = 1e5

    # Sea surface configuration
    s.sea.wind = wind

    # Small optical thickness
    #s.ap.SetPressure(1013.25)
    s.aer.aotref = 0.0

    # Set view level at TOA
    s.view.level = 1
    tau = np.array([])
    rhor0 = np.array([])
    if table:
        tau = ray.getTaur()
    else:
        tau = tau_f(wl)
    for idx, val in np.ndenumerate(wl):
        s.wa = val/1e3
        s.ap.SetMot(tau[idx])
        s.run()
        rho_f = interp1d(s.outputs.vsvza.vza,s.outputs.vsvza.I) 
        rhor0 = np.append(rhor0, rho_f(view))
    
    T = np.exp(-(tau)*(1/np.cos(np.pi*view/180.0)+1/np.cos(np.pi*s.ang.thetas/180.0)))
    # Set view level at TOA
    
    surface5 = np.array([])
    surface10 = np.array([])
    for idx, val in np.ndenumerate(wl):
        s.wa = val/1e3
        s.ap.SetMot(0.0005)
        s.view.level = 1
        s.run()
        rho_f = interp1d(s.outputs.vsvza.vza,s.outputs.vsvza.I) 
        surface5 = np.append(surface5, rho_f(view))
        
        s.ap.SetMot(0.0010)
        s.view.level = 1
        s.run()
        rho_f = interp1d(s.outputs.vsvza.vza,s.outputs.vsvza.I) 
        surface10 = np.append(surface10, rho_f(view))
        
    surface5 = surface5/np.exp(-(0.0005)*(1/np.cos(np.pi*view/180.0)+1/np.cos(np.pi*s.ang.thetas/180.0)))
    surface10 = surface10/np.exp(-(0.0010)*(1/np.cos(np.pi*view/180.0)+1/np.cos(np.pi*s.ang.thetas/180.0)))
    surface = 2*surface5-surface10
    return rhor0 - T*surface
```
![fig:sum](https://user-images.githubusercontent.com/2727433/59035199-25ceb180-8843-11e9-9134-5bd23a8e21a1.png)

![fig:ray](https://user-images.githubusercontent.com/2727433/59035225-33843700-8843-11e9-917d-f29f49b39345.png)

![fig:logray](https://user-images.githubusercontent.com/2727433/59035238-37b05480-8843-11e9-87bd-fa1cfada8427.png)

![fig:difray](https://user-images.githubusercontent.com/2727433/59035249-4139bc80-8843-11e9-9e0f-d8ff27d8a41e.png)

We also computed the error for different angular conditions

![fig:map-abs](https://user-images.githubusercontent.com/2727433/59035313-63cbd580-8843-11e9-81a7-ab5b91cd9e44.png)

![fig:map-rel](https://user-images.githubusercontent.com/2727433/59035332-6b8b7a00-8843-11e9-9d1b-852d21c59c5d.png)

With these results our error is near or less than $10^{-3}$. However we are waiting for some more precise reference data to perform the final evaluation.

**Comment by fnemina** [comment]
We include the report for the current advances in Rayleigh/Molecular scattering.

[Report_23May2019_Rayleigh.pdf](https://github.com/fnemina/AtmosphericCorrection/files/3261702/Report_23May2019_Rayleigh.pdf)

**Comment by fnemina** [comment]
We've got aditional data to compare from [Rayleigh](http://neural0.ucsd.edu/jtan/Rayleigh.html). Also Smart-G comparison data should be available soon.

**Comment by fnemina** [comment]
Less than 1% is acceptable as the error between the OSOAA and AF codes. We will then implement a test using this two terms.

**Comment by fnemina** [comment]
The simulations were repeated for SeaWiFS bands and the followind values were obtained for the tests

```python
        rhor0 = np.array([0.1104504, 0.08328178, 0.05545878, 0.04769015,
                          0.03386741, 0.01572574, 0.0089373, 0.00587494])
        rhor20 = np.array([0.11166135, 0.08423803, 0.05611876, 0.04826359,
                           0.03428078, 0.01591932, 0.0090468, 0.00594655])
        rhor40 = np.array([0.11840034, 0.08965806, 0.05994928, 0.05161227,
                           0.03672544, 0.0170893, 0.00971673, 0.00638773])
```

for the parameters

```python
sun = 30
phi = 90
wind = lut.wl412.sigma[2]**2/0.00534
wind2 = (0.003+0.00512*wind)/0.00534
thetav=2.282
thetav=20.0018

**Comment by fnemina** [comment]
Test implemented for the default behaviour. This will be considered closed for the time being.

**Comment by fnemina** [comment]
We made our first implementation of custom LUTs for the seawifs wavelengths using the OSOAA code.

[seawifs-osoaa.zip](https://github.com/fnemina/AtmosphericCorrection/files/3397261/seawifs-osoaa.zip)

The code was validated against the OSOAA code as the previous LUTs. This comparison should give us error close to zero. The differences existing should come from the parameters chosen to make the LUTs, specially the number of azimuth angles. For the generation of these tables 11 evenly distributed angles between -180 and 180 degrees were chosen.

An error of 10^-5 or less seems to be consistent with the Fourier series calculation but might be improved.

![fig:difray](https://user-images.githubusercontent.com/2727433/61298396-82af7700-a7b4-11e9-9112-773158a8d91d.png)
![fig:relray](https://user-images.githubusercontent.com/2727433/61298621-f18cd000-a7b4-11e9-8d2c-840f052747b6.png)
![fig:togray](https://user-images.githubusercontent.com/2727433/61298440-96f37400-a7b4-11e9-9e93-c76933f7b231.png)
_Rayleigh error between LUT and OSOAA_

![fig:map-abs](https://user-images.githubusercontent.com/2727433/61298472-a5da2680-a7b4-11e9-9b44-d92c6e441c6f.png)
![fig:map-rel](https://user-images.githubusercontent.com/2727433/61298479-a83c8080-a7b4-11e9-9440-5d26daa51fe4.png)
_Angular differences. They are shown in a logarithm scale_

**Comment by QiaoFeng0419** [comment]
I use the method you mentioned to compare NASA Seawifs Rayleigh lookup table with OSOAA Rayleigh scattering.
But there are some differences between my results and yours.
My results:
![fig_Relative error](https://user-images.githubusercontent.com/15885479/61340370-9ae6cb00-a874-11e9-9c93-bfc53d5f87c9.png)
Relative error is as high as 10%.
My code is [here](https://github.com/QiaoFeng0419/Atmospheric-correction-for-GOCI/blob/master/Rayleigh/CompareRayleighBetweenOSOAAandSeaDAS.py)
So, i have some question:

1. The `tau` which in NASA Seawifs Rayleigh lookup table cannot be used to calculate transmittance because OSOAA has its own Tau.

2. What is the step size of the parameters in the Rayleigh scattering lookup table you generated? Can you share your code?
